version: "3.1"

# Set the language
language: en

# NLU pipeline
pipeline:
- name: WhitespaceTokenizer          # splits text into words
- name: RegexFeaturizer              # handles regex features
- name: LexicalSyntacticFeaturizer   # adds syntactic features
- name: CountVectorsFeaturizer       # bag-of-words features
- name: CountVectorsFeaturizer
  analyzer: char_wb                  # character n-grams
- name: DIETClassifier               # main intent & entity classifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper          # maps synonyms to canonical values
- name: ResponseSelector             # FAQ matching
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

# Policies for dialogue management
policies:
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true

- name: MemoizationPolicy              # remembers exact conversation paths
  max_history: 5

- name: TEDPolicy                      # ML-based policy
  max_history: 10
  epochs: 100
  batch_size: 32

- name: UnexpecTEDIntentPolicy         # handles unexpected intents
assistant_id: 20250918-105428-coplanar-wrap
